version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - "4000:80"
    volumes:
      - /usr/src/practice-deploy-backend/node_modules
      - ./backend:/usr/src/practice-deploy-backend

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /usr/src/practice-deploy-frontend/node_modules
      - ./frontend:/usr/src/practice-deploy-frontend
