name: practice-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build the backend docker image
        run: docker build -t com6511/practice-deploy-backend ./backend

      - name: build the nginx docker image
        run: docker build -t com6511/practice-deploy-nginx ./nginx

      - name: login to dockerhub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: push the backend docker image
        run: docker push com6511/practice-deploy-backend

      - name: push the nginx docker image
        run: docker push com6511/practice-deploy-nginx

  # deploy:
  #   runs-on: ubuntu-latest
