name: practice-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Backend Build and push
        uses: docker/build-push-action@v2
        with:
          image: com6511/practice-deploy-backend
          context: ./backend
          push: true
          tags: user/app:latest

      - name: Nginx Build and push
        uses: docker/build-push-action@v2
        with:
          image: com6511/practice-deploy-nginx
          context: ./nginx
          push: true
          tags: user/app:latest

  # deploy:
  #   runs-on: ubuntu-latest
