name: practice-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Backend Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: user/app:latest

      # - name: Nginx Build and push
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: com6511/practice-deploy-nginx
      #     context: ./nginx
      #     push: true
      #     tags: user/app:latest

  # deploy:
  #   runs-on: ubuntu-latest
